### ISSUE TITLE
Code variable renaming/refactoring 

### ISSUE THREAD

**Issue by MBastiampillai** [Songtone/SOEN341TEAMF#120]
Changing variable names so that it fits the proper programming naming convention without harming the code. Refactoring will be done if possible to make the code more efficient.

**Story Points:** 1

**Acceptance Test:**

For all modified files, 
A compiler check must be passed to ensure proper syntax,
A manual verification of the functionality of the website must be completed

**Comment by JKukulsky** [comment]
@MBastiampillai You can't forget to close your issues after your branch has been pulled in. It looks as though this issue was left uncompleted.

**Merged Pull Request:** Code variable renaming/refactoring #124

Acceptance test **PASSED**

Like I said in the Facebook Chat: In the pull request, you need to put a link to the issue your branch originated from. Once the branch is merged, put a closing comment on your issue with the pull request number. Also in that closing comment, write how you verified it met your Acceptance test. Because you should have written an acceptance test for your issue #120. Look at the closed issue #84 for reference.

**Comment by JKukulsky** [comment]
@MBastiampillai You can't forget to close your issues after your branch has been pulled in. It looks as though this issue was left uncompleted.

**Merged Pull Request:** Code variable renaming/refactoring #124

Acceptance test **PASSED**

Like I said in the Facebook Chat: "In the pull request, you need to put a link to the issue your branch originated from. Once the branch is merged, put a closing comment on your issue with the pull request number. Also in that closing comment, write how you verified your Acceptance test. Because you should have written an acceptance test for your issue #120. Look at the closed issue #84 for reference."
